#### **Installing dependencies**

In [1]:
!pip install transformers sentencepiece datasets tqdm rouge -qq

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 183.9/183.9 kB 6.1 MB/s eta 0:00:00
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
gcsfs 2024.10.0 requires fsspec==2024.10.0, but you have fsspec 2024.12.0 which is incompatible.
torch 2.5.1+cu124 requires nvidia-cublas-cu12==12.4.5.8; platform_system == "Linux" and platform_machine == "x86_64", but you have nvidia-cublas-cu12 12.8.4.1 which is incompatible.
torch 2.5.1+cu124 requires nvidia-cudnn-cu12==9.1.0.70; platform_system == "Linux" and platform_machine == "x86_64", but you have nvidia-cudnn-cu12 9.3.0.75 which is incompatible.
torch 2.5.1+cu124 requires nvidia-cufft-cu12==11.2.1.3; platform_system == "Linux" and platform_machine == "x86_64", but you have nvidia-cufft-cu12 11.3.3.83 which is incompatible.
torch 2.5.1+cu124 requires nvidia-curand-cu12==10.3.5.147; platform_system == "Linux" and platform_machine == "x86_64", but you have nvidia-curand-cu12 10.3.9.90 which is incompatible.
torch 2.5.1+cu124 requires nvidia-cusolver-cu12==11.6.1.9; platform_system == "Linux" and platform_machine == "x86_64", but you have nvidia-cusolver-cu12 11.7.3.90 which is incompatible.
torch 2.5.1+cu124 requires nvidia-cusparse-cu12==12.3.1.170; platform_system == "Linux" and platform_machine == "x86_64", but you have nvidia-cusparse-cu12 12.5.8.93 which is incompatible.
torch 2.5.1+cu124 requires nvidia-nvjitlink-cu12==12.4.127; platform_system == "Linux" and platform_machine == "x86_64", but you have nvidia-nvjitlink-cu12 12.8.93 which is incompatible.
bigframes 1.36.0 requires rich<14,>=12.4.4, but you have rich 14.0.0 which is incompatible.

In [2]:
import torch
import pandas as pd
from rouge import Rouge
from transformers import AutoModelForSeq2SeqLM, AutoTokenizer

import plotly.express as px
import matplotlib.pyplot as plt

from plotly.offline import init_notebook_mode
init_notebook_mode(connected=True)

In [3]:
from datasets import load_dataset
ds = load_dataset("csebuetnlp/xlsum", "hindi", split='all')
data = ds.to_pandas()
data = data.sample(frac = 0.125)

README.md:   0%|          | 0.00/14.6k [00:00<?, ?B/s]

xlsum.py:   0%|          | 0.00/4.55k [00:00<?, ?B/s]

0000.parquet:   0%|          | 0.00/187M [00:00<?, ?B/s]

0001.parquet:   0%|          | 0.00/19.6M [00:00<?, ?B/s]

0000.parquet:   0%|          | 0.00/21.5M [00:00<?, ?B/s]

0000.parquet:   0%|          | 0.00/21.4M [00:00<?, ?B/s]

Generating train split:   0%|          | 0/70778 [00:00<?, ? examples/s]

Generating test split:   0%|          | 0/8847 [00:00<?, ? examples/s]

Generating validation split:   0%|          | 0/8847 [00:00<?, ? examples/s]

In [4]:
data = data.drop(['id', 'url'], axis=1)
data

,title,summary,text
62032,मोदी का उपग्रह के ज़रिए संबोधन,गुजरात के मुख्यमंत्री नरेंद्र मोदी ने अमरीकी न...,ग़ौरतलब है कि अमरीका ने पिछले सप्ताह नरेंद्र म...
41064,कोरोना वायरस: लॉकडाउन में क्या बंद और क्या खुल...,जनता कर्फ़्यू को गंभीरता से लेने पर प्रधानमंत्...,उन्होंने ट्वीट किया है कि 'देशवासियों ने बता द...
52698,कलाम ने बच्चों से सपने देखने को कहा,भारत के राष्ट्रपति डॉ. एपीजे अब्दुल कलाम ने मध...,"उन्होंने कहा कि सड़क, बिजली और कंप्यूटर जैसी स..."
58868,"ऑस्ट्रेलिया दवाब में, पाँच विकेट गिरे",मोहाली टेस्ट के चौथे दिन ऑस्ट्रेलिया ने 516 रन...,सोमवार को भारत ने अपनी दूसरी पारी कुल 314 रन ब...
53989,'स्पिन आक्रमण के लिए तैयार हैं',टेस्ट मैच शृंखला के लिए भारत पहुंची ऑस्ट्रेलिय...,भारत के दौरे में रिकी पोंटिंग अक्सर स्पिन गेंद...
...,...,...,...
61977,कोविड से बेटे की मौत पर बोले सीताराम येचुरी- म...,कम्युनिस्ट पार्टी ऑफ इंडिया (मार्क्सवादी) यानी...,"अपने ट्वीट में येचुरी ने डॉक्टरों, नर्सों, फ्र..."
42256,पीएम मोदी के कोलकाता दौरे से राजनीति गर्म,नेशनल रजिस्टर ऑफ़ सिटिज़नशिप (एनआरसी) और नागरि...,मोदी शनिवार को कोलकाता आएंगे. वाम दलों और कांग...
25978,अमिताभ को टैक्स चोरी का नोटिस,सुप्रीम कोर्ट ने टैक्स चुराने के मामले में बॉल...,आयकर विभाग का कहना है कि अमिताभ ने टैक्स बचाया...
26697,"आज की पाँच बड़ी ख़बरें: रफ़ाल पर नई जानकारी, स...",भारत और फ़्रांस के बीच हुए रफ़ाल सौदे को लेकर ...,मीडियापार्ट ने डासो एविएशन के आंतरिक दस्तावेज़...
83821,मुरली दस शीर्ष खिलाड़ियों में नहीं,आईसीसी की नई वनडे रैंकिंग में मास्टर ब्लास्टर ...,777 अंक लेकर सचिन दूसरे नंबर पर हैं तो 792 अंक...

In [5]:
text = data['text']
goldsummary = data['summary']

### **Model1 : BART**

In [6]:
bart_checkpoint = "ai4bharat/IndicBART"

In [7]:
device = "cuda" if torch.cuda.is_available() else "cpu"

In [8]:
tokenizer_bart = AutoTokenizer.from_pretrained(bart_checkpoint, 
                                               do_lower_case=False, 
                                               use_fast=False, 
                                               keep_accents=True)

model_bart = AutoModelForSeq2SeqLM.from_pretrained(bart_checkpoint).to(device)

tokenizer_config.json:   0%|          | 0.00/498 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/832 [00:00<?, ?B/s]

spiece.model:   0%|          | 0.00/1.90M [00:00<?, ?B/s]

added_tokens.json:   0%|          | 0.00/221 [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/398 [00:00<?, ?B/s]

2025-04-24 21:55:11.721881: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:477] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
E0000 00:00:1745531711.922959      19 cuda_dnn.cc:8310] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
E0000 00:00:1745531711.978545      19 cuda_blas.cc:1418] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered

pytorch_model.bin:   0%|          | 0.00/976M [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/976M [00:00<?, ?B/s]

In [9]:
bos_id = tokenizer_bart._convert_token_to_id_with_added_voc("<s>")
eos_id = tokenizer_bart._convert_token_to_id_with_added_voc("</s>")
pad_id = tokenizer_bart._convert_token_to_id_with_added_voc("<pad>")

In [10]:
%%time

from tqdm import tqdm

SystemSummary = []

for i, input_text in tqdm(enumerate(text), total=len(text), desc="Generating Summaries"):
    inp = tokenizer_bart(input_text, add_special_tokens=False, 
                         truncation=True, return_tensors="pt", 
                         padding='max_length', max_length=1024)['input_ids'].to(device)  
    
    model_output = model_bart.generate(inp, use_cache=True, 
                                        num_beams=4, 
                                        max_length=70, 
                                        min_length=30, 
                                        early_stopping=True, 
                                        pad_token_id=pad_id,
                                        bos_token_id=bos_id, 
                                        eos_token_id=eos_id, 
                                        decoder_start_token_id=tokenizer_bart._convert_token_to_id_with_added_voc("<2en>"))
    
    decoded_output = tokenizer_bart.decode(model_output[0], 
                                    skip_special_tokens=True, 
                                    clean_up_tokenization_spaces=False)
    
    SystemSummary.append(decoded_output)

Generating Summaries:   0%|          | 0/11059 [00:00<?, ?it/s]
Generating Summaries:   0%|          | 1/11059 [00:01<6:05:22,  1.98s/it]
Generating Summaries:   0%|          | 2/11059 [00:02<4:05:19,  1.33s/it]
Generating Summaries:   0%|          | 3/11059 [00:03<2:56:57,  1.04it/s]
Generating Summaries:   0%|          | 4/11059 [00:03<2:24:47,  1.27it/s]
Generating Summaries:   0%|          | 5/11059 [00:04<2:07:07,  1.45it/s]
Generating Summaries:   0%|          | 6/11059 [00:04<1:56:49,  1.58it/s]
Generating Summaries:   0%|          | 7/11059 [00:05<1:49:33,  1.68it/s]
Generating Summaries:   0%|          | 8/11059 [00:05<1:45:48,  1.74it/s]
Generating Summaries:   0%|          | 9/11059 [00:06<1:45:41,  1.74it/s]
Generating Summaries:   0%|          | 10/11059 [00:07<1:45:13,  1.75it/s]
Generating Summaries:   0%|          | 11/11059 [00:07<1:44:45,  1.76it/s]
Generating Summaries:   0%|          | 12/11059 [00:08<1:43:16,  1.78it/s]
Generating Summaries:   0%|          | 13/11059 [00:08<1:40:58,  1.82it/s]
Generating Summaries:   0%|          | 14/11059 [00:09<1:39:25,  1.85it/s]
Generating Summaries:   0%|          | 15/11059 [00:09<1:39:30,  1.85it/s]
Generating Summaries:   0%|          | 16/11059 [00:10<1:39:08,  1.86it/s]
Generating Summaries:   0%|          | 17/11059 [00:10<1:38:31,  1.87it/s]
Generating Summaries:   0%|          | 18/11059 [00:11<1:37:56,  1.88it/s]
Generating Summaries:   0%|          | 19/11059 [00:11<1:36:34,  1.91it/s]
Generating Summaries:   0%|          | 20/11059 [00:12<1:35:53,  1.92it/s]
Generating Summaries:   0%|          | 21/11059 [00:12<1:35:50,  1.92it/s]
Generating Summaries:   0%|          | 22/11059 [00:13<1:37:25,  1.89it/s]
Generating Summaries:   0%|          | 23/11059 [00:14<1:36:54,  1.90it/s]
Generating Summaries:   0%|          | 24/11059 [00:14<1:36:29,  1.91it/s]
Generating Summaries:   0%|          | 25/11059 [00:15<1:36:13,  1.91it/s]
Generating Summaries:   0%|          | 26/11059 [00:15<1:36:04,  1.91it/s]
Generating Summaries:   0%|          | 27/11059 [00:16<1:35:40,  1.92it/s]
Generating Summaries:   0%|          | 28/11059 [00:16<1:35:43,  1.92it/s]
Generating Summaries:   0%|          | 29/11059 [00:17<1:35:26,  1.93it/s]
Generating Summaries:   0%|          | 30/11059 [00:17<1:34:39,  1.94it/s]
Generating Summaries:   0%|          | 31/11059 [00:18<1:35:45,  1.92it/s]
Generating Summaries:   0%|          | 32/11059 [00:18<1:46:57,  1.72it/s]
Generating Summaries:   0%|          | 33/11059 [00:19<1:44:19,  1.76it/s]
Generating Summaries:   0%|          | 34/11059 [00:19<1:41:50,  1.80it/s]
Generating Summaries:   0%|          | 35/11059 [00:20<1:41:12,  1.82it/s]
Generating Summaries:   0%|          | 36/11059 [00:21<1:43:08,  1.78it/s]
Generating Summaries:   0%|          | 37/11059 [00:21<1:41:57,  1.80it/s]
Generating Summaries:   0%|          | 38/11059 [00:22<1:41:00,  1.82it/s]
Generating Summaries:   0%|          | 39/11059 [00:22<1:39:36,  1.84it/s]
Generating Summaries:   0%|          | 40/11059 [00:23<1:39:24,  1.85it/s]
Generating Summaries:   0%|          | 41/11059 [00:23<1:38:43,  1.86it/s]
Generating Summaries:   0%|          | 42/11059 [00:24<1:38:29,  1.86it/s]
Generating Summaries:   0%|          | 43/11059 [00:24<1:37:23,  1.89it/s]
Generating Summaries:   0%|          | 44/11059 [00:25<1:37:19,  1.89it/s]
Generating Summaries:   0%|          | 45/11059 [00:25<1:36:39,  1.90it/s]
Generating Summaries:   0%|          | 46/11059 [00:26<1:36:07,  1.91it/s]
Generating Summaries:   0%|          | 47/11059 [00:26<1:35:17,  1.93it/s]
Generating Summaries:   0%|          | 48/11059 [00:27<1:35:03,  1.93it/s]
Generating Summaries:   0%|          | 49/11059 [00:27<1:34:49,  1.94it/s]
Generating Summaries:   0%|          | 50/11059 [00:28<1:34:00,  1.95it/s]
Generating Summaries:   0%|          | 51/11059 [00:28<1:33:53,  1.95it/s]
Generating Summaries:   0%|          | 52/11059 [00:29<1:34:08,  1.95it/s]
Generating Summaries:   0%|          | 53/11059 [00:29<1:34:52,  1.93it/s]
Generating Summaries:   0%|          | 54/11059 [00:30<1:35:05,  1.93it/s]
Generating Summaries:   0%|          | 55/11059 [00:30<1:34:42,  1.94it/s]
Generating Summaries:   1%|          | 56/11059 [00:31<1:34:28,  1.94it/s]
Generating Summaries:   1%|          | 57/11059 [00:32<1:34:26,  1.94it/s]
Generating Summaries:   1%|          | 58/11059 [00:32<1:34:58,  1.93it/s]
Generating Summaries:   1%|          | 59/11059 [00:33<1:34:56,  1.93it/s]
Generating Summaries:   1%|          | 60/11059 [00:33<1:35:06,  1.93it/s]
Generating Summaries:   1%|          | 61/11059 [00:34<1:34:39,  1.94it/s]
Generating Summaries:   1%|          | 62/11059 [00:34<1:34:20,  1.94it/s]
Generating Summaries:   1%|          | 63/11059 [00:35<1:34:45,  1.93it/s]
Generating Summaries:   1%|          | 64/11059 [00:35<1:34:48,  1.93it/s]
Generating Summaries:   1%|          | 65/11059 [00:36<1:35:04,  1.93it/s]
Generating Summaries:   1%|          | 66/11059 [00:36<1:34:39,  1.94it/s]
Generating Summaries:   1%|          | 67/11059 [00:37<1:34:50,  1.93it/s]
Generating Summaries:   1%|          | 68/11059 [00:37<1:34:48,  1.93it/s]
Generating Summaries:   1%|          | 69/11059 [00:38<1:34:50,  1.93it/s]
Generating Summaries:   1%|          | 70/11059 [00:38<1:34:18,  1.94it/s]
Generating Summaries:   1%|          | 71/11059 [00:39<1:34:39,  1.93it/s]
Generating Summaries:   1%|          | 72/11059 [00:39<1:34:57,  1.93it/s]
Generating Summaries:   1%|          | 73/11059 [00:40<1:37:54,  1.87it/s]
Generating Summaries:   1%|          | 74/11059 [00:40<1:37:18,  1.88it/s]
Generating Summaries:   1%|          | 75/11059 [00:41<1:36:43,  1.89it/s]
Generating Summaries:   1%|          | 76/11059 [00:41<1:36:11,  1.90it/s]
Generating Summaries:   1%|          | 77/11059 [00:42<1:36:03,  1.91it/s]
Generating Summaries:   1%|          | 78/11059 [00:42<1:35:48,  1.91it/s]
Generating Summaries:   1%|          | 79/11059 [00:43<1:35:50,  1.91it/s]
Generating Summaries:   1%|          | 80/11059 [00:43<1:35:12,  1.92it/s]
Generating Summaries:   1%|          | 81/11059 [00:44<1:34:57,  1.93it/s]
Generating Summaries:   1%|          | 82/11059 [00:45<1:34:58,  1.93it/s]
Generating Summaries:   1%|          | 83/11059 [00:45<1:34:51,  1.93it/s]
Generating Summaries:   1%|          | 84/11059 [00:46<1:34:00,  1.95it/s]
Generating Summaries:   1%|          | 85/11059 [00:46<1:33:35,  1.95it/s]
Generating Summaries:   1%|          | 86/11059 [00:47<1:33:24,  1.96it/s]
Generating Summaries:   1%|          | 87/11059 [00:47<1:33:43,  1.95it/s]
Generating Summaries:   1%|          | 88/11059 [00:48<1:33:41,  1.95it/s]
Generating Summaries:   1%|          | 89/11059 [00:48<1:34:05,  1.94it/s]
Generating Summaries:   1%|          | 90/11059 [00:49<1:34:22,  1.94it/s]
Generating Summaries:   1%|          | 91/11059 [00:49<1:34:27,  1.94it/s]
Generating Summaries:   1%|          | 92/11059 [00:50<1:36:48,  1.89it/s]
Generating Summaries:   1%|          | 93/11059 [00:50<1:36:09,  1.90it/s]
Generating Summaries:   1%|          | 94/11059 [00:51<1:36:10,  1.90it/s]
Generating Summaries:   1%|          | 95/11059 [00:51<1:35:22,  1.92it/s]
Generating Summaries:   1%|          | 96/11059 [00:52<1:36:41,  1.89it/s]
Generating Summaries:   1%|          | 97/11059 [00:52<1:38:37,  1.85it/s]
Generating Summaries:   1%|          | 98/11059 [00:53<1:37:36,  1.87it/s]
Generating Summaries:   1%|          | 99/11059 [00:53<1:36:27,  1.89it/s]
Generating Summaries:   1%|          | 100/11059 [00:54<1:35:29,  1.91it/s]
Generating Summaries:   1%|          | 101/11059 [00:54<1:34:45,  1.93it/s]
Generating Summaries:   1%|          | 102/11059 [00:55<1:34:27,  1.93it/s]
Generating Summaries:   1%|          | 103/11059 [00:55<1:34:04,  1.94it/s]
Generating Summaries:   1%|          | 104/11059 [00:56<1:33:58,  1.94it/s]
Generating Summaries:   1%|          | 105/11059 [00:56<1:33:49,  1.95it/s]
Generating Summaries:   1%|          | 106/11059 [00:57<1:34:03,  1.94it/s]
Generating Summaries:   1%|          | 107/11059 [00:58<1:33:42,  1.95it/s]
Generating Summaries:   1%|          | 108/11059 [00:58<1:33:55,  1.94it/s]
Generating Summaries:   1%|          | 109/11059 [00:59<1:33:55,  1.94it/s]
Generating Summaries:   1%|          | 110/11059 [00:59<1:33:57,  1.94it/s]
Generating Summaries:   1%|          | 111/11059 [01:00<1:36:19,  1.89it/s]
Generating Summaries:   1%|          | 112/11059 [01:00<1:35:38,  1.91it/s]
Generating Summaries:   1%|          | 113/11059 [01:01<1:35:09,  1.92it/s]
Generating Summaries:   1%|          | 114/11059 [01:01<1:35:10,  1.92it/s]
Generating Summaries:   1%|          | 115/11059 [01:02<1:33:57,  1.94it/s]
Generating Summaries:   1%|          | 116/11059 [01:02<1:33:29,  1.95it/s]
Generating Summaries:   1%|          | 117/11059 [01:03<1:33:22,  1.95it/s]
Generating Summaries:   1%|          | 118/11059 [01:03<1:33:32,  1.95it/s]
Generating Summaries:   1%|          | 119/11059 [01:04<1:34:07,  1.94it/s]
Generating Summaries:   1%|          | 120/11059 [01:04<1:34:30,  1.93it/s]
Generating Summaries:   1%|          | 121/11059 [01:05<1:37:38,  1.87it/s]
Generating Summaries:   1%|          | 122/11059 [01:05<1:37:13,  1.87it/s]
Generating Summaries:   1%|          | 123/11059 [01:06<1:36:43,  1.88it/s]
Generating Summaries:   1%|          | 124/11059 [01:06<1:36:54,  1.88it/s]
Generating Summaries:   1%|          | 125/11059 [01:07<1:36:38,  1.89it/s]
Generating Summaries:   1%|          | 126/11059 [01:07<1:35:39,  1.90it/s]
Generating Summaries:   1%|          | 127/11059 [01:08<1:35:03,  1.92it/s]
Generating Summaries:   1%|          | 128/11059 [01:08<1:34:49,  1.92it/s]
Generating Summaries:   1%|          | 129/11059 [01:09<1:35:00,  1.92it/s]
Generating Summaries:   1%|          | 130/11059 [01:10<1:38:59,  1.84it/s]
Generating Summaries:   1%|          | 131/11059 [01:10<1:38:50,  1.84it/s]
Generating Summaries:   1%|          | 132/11059 [01:11<1:37:06,  1.88it/s]
Generating Summaries:   1%|          | 133/11059 [01:11<1:36:26,  1.89it/s]
Generating Summaries:   1%|          | 134/11059 [01:12<1:36:38,  1.88it/s]
Generating Summaries:   1%|          | 135/11059 [01:12<1:35:57,  1.90it/s]
Generating Summaries:   1%|          | 136/11059 [01:13<1:35:00,  1.92it/s]
Generating Summaries:   1%|          | 137/11059 [01:13<1:35:27,  1.91it/s]
Generating Summaries:   1%|          | 138/11059 [01:14<1:34:32,  1.93it/s]
Generating Summaries:   1%|▏         | 139/11059 [01:14<1:34:03,  1.93it/s]
Generating Summaries:   1%|▏         | 140/11059 [01:15<1:33:42,  1.94it/s]
Generating Summaries:   1%|▏         | 141/11059 [01:15<1:33:45,  1.94it/s]
Generating Summaries:   1%|▏         | 142/11059 [01:16<1:34:09,  1.93it/s]
Generating Summaries:   1%|▏         | 143/11059 [01:16<1:33:35,  1.94it/s]
Generating Summaries:   1%|▏         | 144/11059 [01:17<1:33:13,  1.95it/s]
Generating Summaries:   1%|▏         | 145/11059 [01:17<1:33:23,  1.95it/s]
Generating Summaries:   1%|▏         | 146/11059 [01:18<1:33:13,  1.95it/s]
Generating Summaries:   1%|▏         | 147/11059 [01:18<1:33:38,  1.94it/s]
Generating Summaries:   1%|▏         | 148/11059 [01:19<1:33:51,  1.94it/s]
Generating Summaries:   1%|▏         | 149/11059 [01:19<1:34:33,  1.92it/s]
Generating Summaries:   1%|▏         | 150/11059 [01:20<1:35:02,  1.91it/s]
Generating Summaries:   1%|▏         | 151/11059 [01:20<1:34:42,  1.92it/s]
Generating Summaries:   1%|▏         | 152/11059 [01:21<1:33:53,  1.94it/s]
Generating Summaries:   1%|▏         | 153/11059 [01:22<1:33:50,  1.94it/s]
Generating Summaries:   1%|▏         | 154/11059 [01:22<1:33:53,  1.94it/s]
Generating Summaries:   1%|▏         | 155/11059 [01:23<1:34:03,  1.93it/s]
Generating Summaries:   1%|▏         | 156/11059 [01:23<1:33:57,  1.93it/s]
Generating Summaries:   1%|▏         | 157/11059 [01:24<1:37:18,  1.87it/s]
Generating Summaries:   1%|▏         | 158/11059 [01:24<1:37:26,  1.86it/s]
Generating Summaries:   1%|▏         | 159/11059 [01:25<1:38:33,  1.84it/s]
Generating Summaries:   1%|▏         | 160/11059 [01:25<1:37:02,  1.87it/s]
Generating Summaries:   1%|▏         | 161/11059 [01:26<1:35:53,  1.89it/s]
Generating Summaries:   1%|▏         | 162/11059 [01:26<1:34:24,  1.92it/s]
Generating Summaries:   1%|▏         | 163/11059 [01:27<1:34:44,  1.92it/s]
Generating Summaries:   1%|▏         | 164/11059 [01:27<1:34:44,  1.92it/s]
Generating Summaries:   1%|▏         | 165/11059 [01:28<1:34:20,  1.92it/s]
Generating Summaries:   2%|▏         | 166/11059 [01:28<1:33:44,  1.94it/s]
Generating Summaries:   2%|▏         | 167/11059 [01:29<1:34:00,  1.93it/s]
Generating Summaries:   2%|▏         | 168/11059 [01:29<1:33:54,  1.93it/s]
Generating Summaries:   2%|▏         | 169/11059 [01:30<1:35:12,  1.91it/s]
Generating Summaries:   2%|▏         | 170/11059 [01:30<1:35:20,  1.90it/s]
Generating Summaries:   2%|▏         | 171/11059 [01:31<1:35:14,  1.91it/s]
Generating Summaries:   2%|▏         | 172/11059 [01:31<1:34:34,  1.92it/s]
Generating Summaries:   2%|▏         | 173/11059 [01:32<1:34:03,  1.93it/s]
Generating Summaries:   2%|▏         | 174/11059 [01:33<1:33:58,  1.93it/s]
Generating Summaries:   2%|▏         | 175/11059 [01:33<1:33:26,  1.94it/s]
Generating Summaries:   2%|▏         | 176/11059 [01:34<1:33:23,  1.94it/s]
Generating Summaries:   2%|▏         | 177/11059 [01:34<1:33:47,  1.93it/s]
Generating Summaries:   2%|▏         | 178/11059 [01:35<1:33:31,  1.94it/s]
Generating Summaries:   2%|▏         | 179/11059 [01:35<1:33:36,  1.94it/s]
Generating Summaries:   2%|▏         | 180/11059 [01:36<1:33:17,  1.94it/s]
Generating Summaries:   2%|▏         | 181/11059 [01:36<1:33:31,  1.94it/s]
Generating Summaries:   2%|▏         | 182/11059 [01:37<1:34:03,  1.93it/s]
Generating Summaries:   2%|▏         | 183/11059 [01:37<1:33:58,  1.93it/s]
Generating Summaries:   2%|▏         | 184/11059 [01:38<1:33:35,  1.94it/s]
Generating Summaries:   2%|▏         | 185/11059 [01:38<1:33:22,  1.94it/s]
Generating Summaries:   2%|▏         | 186/11059 [01:39<1:34:10,  1.92it/s]
Generating Summaries:   2%|▏         | 187/11059 [01:39<1:33:56,  1.93it/s]
Generating Summaries:   2%|▏         | 188/11059 [01:40<1:35:33,  1.90it/s]
Generating Summaries:   2%|▏         | 189/11059 [01:40<1:35:02,  1.91it/s]
Generating Summaries:   2%|▏         | 190/11059 [01:41<1:34:58,  1.91it/s]
Generating Summaries:   2%|▏         | 191/11059 [01:41<1:34:44,  1.91it/s]
Generating Summaries:   2%|▏         | 192/11059 [01:42<1:34:43,  1.91it/s]
Generating Summaries:   2%|▏         | 193/11059 [01:42<1:34:55,  1.91it/s]
Generating Summaries:   2%|▏         | 194/11059 [01:43<1:34:21,  1.92it/s]
Generating Summaries:   2%|▏         | 195/11059 [01:43<1:34:10,  1.92it/s]
Generating Summaries:   2%|▏         | 196/11059 [01:44<1:34:08,  1.92it/s]
Generating Summaries:   2%|▏         | 197/11059 [01:44<1:34:05,  1.92it/s]
Generating Summaries:   2%|▏         | 198/11059 [01:45<1:33:58,  1.93it/s]
Generating Summaries:   2%|▏         | 199/11059 [01:45<1:33:26,  1.94it/s]
Generating Summaries:   2%|▏         | 200/11059 [01:46<1:33:45,  1.93it/s]
Generating Summaries:   2%|▏         | 201/11059 [01:47<1:33:07,  1.94it/s]
Generating Summaries:   2%|▏         | 202/11059 [01:47<1:33:26,  1.94it/s]
Generating Summaries:   2%|▏         | 203/11059 [01:48<1:33:50,  1.93it/s]
Generating Summaries:   2%|▏         | 204/11059 [01:48<1:33:46,  1.93it/s]
Generating Summaries:   2%|▏         | 205/11059 [01:49<1:33:48,  1.93it/s]
Generating Summaries:   2%|▏         | 206/11059 [01:49<1:33:42,  1.93it/s]
Generating Summaries:   2%|▏         | 207/11059 [01:50<1:35:31,  1.89it/s]
Generating Summaries:   2%|▏         | 208/11059 [01:50<1:34:06,  1.92it/s]
Generating Summaries:   2%|▏         | 209/11059 [01:51<1:34:08,  1.92it/s]
Generating Summaries:   2%|▏         | 210/11059 [01:51<1:33:57,  1.92it/s]
Generating Summaries:   2%|▏         | 211/11059 [01:52<1:33:41,  1.93it/s]
Generating Summaries:   2%|▏         | 212/11059 [01:52<1:33:36,  1.93it/s]
Generating Summaries:   2%|▏         | 213/11059 [01:53<1:33:08,  1.94it/s]
Generating Summaries:   2%|▏         | 214/11059 [01:53<1:33:23,  1.94it/s]
Generating Summaries:   2%|▏         | 215/11059 [01:54<1:33:22,  1.94it/s]
Generating Summaries:   2%|▏         | 216/11059 [01:54<1:33:26,  1.93it/s]
Generating Summaries:   2%|▏         | 217/11059 [01:55<1:33:11,  1.94it/s]
Generating Summaries:   2%|▏         | 218/11059 [01:55<1:35:13,  1.90it/s]
Generating Summaries:   2%|▏         | 219/11059 [01:56<1:34:41,  1.91it/s]
Generating Summaries:   2%|▏         | 220/11059 [01:56<1:34:41,  1.91it/s]
Generating Summaries:   2%|▏         | 221/11059 [01:57<1:34:15,  1.92it/s]
Generating Summaries:   2%|▏         | 222/11059 [01:57<1:34:32,  1.91it/s]
Generating Summaries:   2%|▏         | 223/11059 [01:58<1:34:34,  1.91it/s]
Generating Summaries:   2%|▏         | 224/11059 [01:58<1:34:04,  1.92it/s]
Generating Summaries:   2%|▏         | 225/11059 [01:59<1:34:02,  1.92it/s]
Generating Summaries:   2%|▏         | 226/11059 [02:00<1:36:04,  1.88it/s]
Generating Summaries:   2%|▏         | 227/11059 [02:00<1:35:02,  1.90it/s]
Generating Summaries:   2%|▏         | 228/11059 [02:01<1:34:55,  1.90it/s]
Generating Summaries:   2%|▏         | 229/11059 [02:01<1:34:22,  1.91it/s]
Generating Summaries:   2%|▏         | 230/11059 [02:02<1:34:22,  1.91it/s]
Generating Summaries:   2%|▏         | 231/11059 [02:02<1:34:04,  1.92it/s]
Generating Summaries:   2%|▏         | 232/11059 [02:03<1:33:58,  1.92it/s]
Generating Summaries:   2%|▏         | 233/11059 [02:03<1:33:44,  1.92it/s]
Generating Summaries:   2%|▏         | 234/11059 [02:04<1:33:07,  1.94it/s]
Generating Summaries:   2%|▏         | 235/11059 [02:04<1:33:32,  1.93it/s]
Generating Summaries:   2%|▏         | 236/11059 [02:05<1:33:49,  1.92it/s]
Generating Summaries:   2%|▏         | 237/11059 [02:05<1:34:02,  1.92it/s]
Generating Summaries:   2%|▏         | 238/11059 [02:06<1:34:18,  1.91it/s]
Generating Summaries:   2%|▏         | 239/11059 [02:06<1:33:35,  1.93it/s]
Generating Summaries:   2%|▏         | 240/11059 [02:07<1:33:18,  1.93it/s]
Generating Summaries:   2%|▏         | 241/11059 [02:07<1:33:07,  1.94it/s]
Generating Summaries:   2%|▏         | 242/11059 [02:08<1:33:39,  1.92it/s]
Generating Summaries:   2%|▏         | 243/11059 [02:08<1:33:34,  1.93it/s]
Generating Summaries:   2%|▏         | 244/11059 [02:09<1:33:53,  1.92it/s]
Generating Summaries:   2%|▏         | 245/11059 [02:09<1:34:00,  1.92it/s]
Generating Summaries:   2%|▏         | 246/11059 [02:10<1:34:09,  1.91it/s]
Generating Summaries:   2%|▏         | 247/11059 [02:10<1:33:52,  1.92it/s]
Generating Summaries:   2%|▏         | 248/11059 [02:11<1:33:16,  1.93it/s]
Generating Summaries:   2%|▏         | 249/11059 [02:12<1:33:11,  1.93it/s]
Generating Summaries:   2%|▏         | 250/11059 [02:12<1:34:55,  1.90it/s]
Generating Summaries:   2%|▏         | 251/11059 [02:13<1:33:14,  1.93it/s]
Generating Summaries:   2%|▏         | 252/11059 [02:13<1:33:08,  1.93it/s]
Generating Summaries:   2%|▏         | 253/11059 [02:14<1:33:27,  1.93it/s]
Generating Summaries:   2%|▏         | 254/11059 [02:14<1:33:38,  1.92it/s]
Generating Summaries:   2%|▏         | 255/11059 [02:15<1:33:27,  1.93it/s]
Generating Summaries:   2%|▏         | 256/11059 [02:15<1:33:28,  1.93it/s]
Generating Summaries:   2%|▏         | 257/11059 [02:16<1:33:04,  1.93it/s]
Generating Summaries:   2%|▏         | 258/11059 [02:16<1:33:25,  1.93it/s]
Generating Summaries:   2%|▏         | 259/11059 [02:17<1:33:20,  1.93it/s]
Generating Summaries:   2%|▏         | 260/11059 [02:17<1:33:27,  1.93it/s]
Generating Summaries:   2%|▏         | 261/11059 [02:18<1:33:01,  1.93it/s]
Generating Summaries:   2%|▏         | 262/11059 [02:18<1:33:04,  1.93it/s]
Generating Summaries:   2%|▏         | 263/11059 [02:19<1:33:26,  1.93it/s]

CPU times: user 1h 35min 28s, sys: 11.8 s, total: 1h 35min 39s
Wall time: 1h 35min 27s

In [11]:
Summaries = pd.DataFrame(list(zip(goldsummary, SystemSummary)), columns =['GoldSummary', 'BartSummary'])
Summaries

,GoldSummary,BartSummary
0,गुजरात के मुख्यमंत्री नरेंद्र मोदी ने अमरीकी न...,ग़ौरतलब है कि अमरीका ने पिछले सप्ताह नरेंद्र म...
1,जनता कर्फ़्यू को गंभीरता से लेने पर प्रधानमंत्...,उन्होंने ट्वीट किया है कि 'देशवासियों ने बता द...
2,भारत के राष्ट्रपति डॉ. एपीजे अब्दुल कलाम ने मध...,"उन्होंने कहा कि सड़क, बिजली और कंप्यूटर जैसी स..."
3,मोहाली टेस्ट के चौथे दिन ऑस्ट्रेलिया ने 516 रन...,सोमवार को भारत ने अपनी दूसरी पारी कुल 314 रन ब...
4,टेस्ट मैच शृंखला के लिए भारत पहुंची ऑस्ट्रेलिय...,भारत के दौरे में रिकी पोंटिंग अक्सर स्पिन गेंद...
...,...,...
11054,कम्युनिस्ट पार्टी ऑफ इंडिया (मार्क्सवादी) यानी...,"अपने ट्वीट में येचुरी ने डॉक्टरों, नर्सों, फ्र..."
11055,नेशनल रजिस्टर ऑफ़ सिटिज़नशिप (एनआरसी) और नागरि...,मोदी शनिवार को कोलकाता आएंगे. वाम दलों और कांग...
11056,सुप्रीम कोर्ट ने टैक्स चुराने के मामले में बॉल...,आयकर विभाग का कहना है कि अमिताभ ने टैक्स बचाया...
11057,भारत और फ़्रांस के बीच हुए रफ़ाल सौदे को लेकर ...,मीडियापार्ट ने डासो एविएशन के आंतरिक दस्तावेज़...
11058,आईसीसी की नई वनडे रैंकिंग में मास्टर ब्लास्टर ...,777 अंक लेकर सचिन दूसरे नंबर पर हैं तो 792 अंक...

In [12]:
rouge = Rouge()
score = rouge.get_scores(Summaries['BartSummary'], Summaries['GoldSummary'], avg=True)
BartRouge = pd.DataFrame(score).set_index([['recall','precision','f-measure']])
BartRouge

            rouge-1   rouge-2   rouge-l
recall     0.373179  0.093419  0.315025
precision  0.204923  0.045523  0.172315
f-measure  0.259175  0.059797  0.218148

### **Model2 : T5**

In [13]:
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
t5_checkpoint = "csebuetnlp/mT5_multilingual_XLSum"

tokenizer_t5 = AutoTokenizer.from_pretrained(t5_checkpoint)
model_t5 = AutoModelForSeq2SeqLM.from_pretrained(t5_checkpoint).to(device)

tokenizer_config.json:   0%|          | 0.00/375 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/730 [00:00<?, ?B/s]

spiece.model:   0%|          | 0.00/4.31M [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/65.0 [00:00<?, ?B/s]

You are using the default legacy behaviour of the <class 'transformers.models.t5.tokenization_t5.T5Tokenizer'>. This is expected, and simply means that the `legacy` (previous) behavior will be used so nothing changes for you. If you want to use the new behaviour, set `legacy=False`. This should only be set if you understand what it means, and thoroughly read the reason why this was added as explained in https://github.com/huggingface/transformers/pull/24565
/usr/local/lib/python3.11/dist-packages/transformers/convert_slow_tokenizer.py:559: UserWarning:

The sentencepiece tokenizer that you are converting to a fast tokenizer uses the byte fallback option which is not implemented in the fast tokenizers. In practice this means that the fast version of the tokenizer can produce unknown tokens whereas the sentencepiece version would have converted these unknown tokens into a sequence of byte tokens matching the original piece of text.

pytorch_model.bin:   0%|          | 0.00/2.33G [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/2.33G [00:00<?, ?B/s]

In [14]:
%%time

from tqdm import tqdm

SystemSummary1 = []

for i, input_text in tqdm(enumerate(text), total=len(text), desc="Generating Summaries"):
    input_ids = tokenizer_t5(input_text,
                             return_tensors="pt",
                             padding="max_length",
                             truncation=True,
                             max_length=768)["input_ids"].to(device) 

    model_output = model_t5.generate(input_ids=input_ids,
                                     num_beams=4,
                                     max_length=70,
                                     min_length=30,
                                     no_repeat_ngram_size=2,
                                     early_stopping=True)

    decoded_output = tokenizer_t5.decode(model_output[0],
                                  skip_special_tokens=True,
                                  clean_up_tokenization_spaces=False)
    
    SystemSummary1.append(decoded_output)

Generating Summaries:   0%|          | 0/11059 [00:00<?, ?it/s]
Generating Summaries:   0%|          | 1/11059 [00:01<6:03:51,  1.97s/it]
Generating Summaries:   0%|          | 2/11059 [00:03<4:27:10,  1.45s/it]
Generating Summaries:   0%|          | 3/11059 [00:04<3:51:57,  1.26s/it]
Generating Summaries:   0%|          | 4/11059 [00:05<3:37:25,  1.18s/it]
Generating Summaries:   0%|          | 5/11059 [00:06<3:29:07,  1.14s/it]
Generating Summaries:   0%|          | 6/11059 [00:07<3:34:51,  1.17s/it]
Generating Summaries:   0%|          | 7/11059 [00:08<3:42:06,  1.21s/it]
Generating Summaries:   0%|          | 8/11059 [00:10<4:07:13,  1.34s/it]
Generating Summaries:   0%|          | 9/11059 [00:11<3:52:55,  1.26s/it]
Generating Summaries:   0%|          | 10/11059 [00:12<3:32:33,  1.15s/it]
Generating Summaries:   0%|          | 11/11059 [00:13<3:54:58,  1.28s/it]
Generating Summaries:   0%|          | 12/11059 [00:14<3:26:28,  1.12s/it]
Generating Summaries:   0%|          | 13/11059 [00:15<3:20:41,  1.09s/it]
Generating Summaries:   0%|          | 14/11059 [00:17<3:37:32,  1.18s/it]
Generating Summaries:   0%|          | 15/11059 [00:18<3:45:33,  1.23s/it]
Generating Summaries:   0%|          | 16/11059 [00:19<3:49:11,  1.25s/it]
Generating Summaries:   0%|          | 17/11059 [00:21<4:06:31,  1.34s/it]
Generating Summaries:   0%|          | 18/11059 [00:22<3:42:19,  1.21s/it]
Generating Summaries:   0%|          | 19/11059 [00:23<3:35:40,  1.17s/it]
Generating Summaries:   0%|          | 20/11059 [00:24<3:56:49,  1.29s/it]
Generating Summaries:   0%|          | 21/11059 [00:26<3:55:04,  1.28s/it]
Generating Summaries:   0%|          | 22/11059 [00:26<3:35:39,  1.17s/it]
Generating Summaries:   0%|          | 23/11059 [00:28<3:27:08,  1.13s/it]
Generating Summaries:   0%|          | 24/11059 [00:28<3:14:32,  1.06s/it]
Generating Summaries:   0%|          | 25/11059 [00:30<3:25:30,  1.12s/it]
Generating Summaries:   0%|          | 26/11059 [00:31<3:15:19,  1.06s/it]
Generating Summaries:   0%|          | 27/11059 [00:31<3:03:03,  1.00it/s]
Generating Summaries:   0%|          | 28/11059 [00:32<3:06:33,  1.01s/it]
Generating Summaries:   0%|          | 29/11059 [00:33<3:01:34,  1.01it/s]
Generating Summaries:   0%|          | 30/11059 [00:34<3:01:57,  1.01it/s]
Generating Summaries:   0%|          | 31/11059 [00:36<3:33:21,  1.16s/it]
Generating Summaries:   0%|          | 32/11059 [00:37<3:25:12,  1.12s/it]
Generating Summaries:   0%|          | 33/11059 [00:38<3:18:55,  1.08s/it]
Generating Summaries:   0%|          | 34/11059 [00:39<3:26:52,  1.13s/it]
Generating Summaries:   0%|          | 35/11059 [00:41<3:44:02,  1.22s/it]
Generating Summaries:   0%|          | 36/11059 [00:41<3:23:03,  1.11s/it]
Generating Summaries:   0%|          | 37/11059 [00:43<3:19:00,  1.08s/it]
Generating Summaries:   0%|          | 38/11059 [00:43<3:12:07,  1.05s/it]
Generating Summaries:   0%|          | 39/11059 [00:45<3:20:21,  1.09s/it]
Generating Summaries:   0%|          | 40/11059 [00:46<3:45:50,  1.23s/it]
Generating Summaries:   0%|          | 41/11059 [00:47<3:46:16,  1.23s/it]
Generating Summaries:   0%|          | 42/11059 [00:48<3:26:59,  1.13s/it]
Generating Summaries:   0%|          | 43/11059 [00:50<3:34:15,  1.17s/it]
Generating Summaries:   0%|          | 44/11059 [00:51<3:19:20,  1.09s/it]
Generating Summaries:   0%|          | 45/11059 [00:52<3:45:49,  1.23s/it]
Generating Summaries:   0%|          | 46/11059 [00:53<3:29:11,  1.14s/it]
Generating Summaries:   0%|          | 47/11059 [00:55<3:53:20,  1.27s/it]
Generating Summaries:   0%|          | 48/11059 [00:56<3:48:12,  1.24s/it]
Generating Summaries:   0%|          | 49/11059 [00:57<3:21:09,  1.10s/it]
Generating Summaries:   0%|          | 50/11059 [00:57<3:11:44,  1.04s/it]
Generating Summaries:   0%|          | 51/11059 [00:59<3:27:54,  1.13s/it]
Generating Summaries:   0%|          | 52/11059 [01:00<3:45:32,  1.23s/it]
Generating Summaries:   0%|          | 53/11059 [01:01<3:25:12,  1.12s/it]
Generating Summaries:   0%|          | 54/11059 [01:02<3:31:20,  1.15s/it]
Generating Summaries:   0%|          | 55/11059 [01:04<3:35:34,  1.18s/it]
Generating Summaries:   1%|          | 56/11059 [01:05<3:36:53,  1.18s/it]
Generating Summaries:   1%|          | 57/11059 [01:06<3:40:44,  1.20s/it]
Generating Summaries:   1%|          | 58/11059 [01:07<3:48:33,  1.25s/it]
Generating Summaries:   1%|          | 59/11059 [01:09<3:50:35,  1.26s/it]
Generating Summaries:   1%|          | 60/11059 [01:10<4:07:25,  1.35s/it]
Generating Summaries:   1%|          | 61/11059 [01:11<3:49:14,  1.25s/it]
Generating Summaries:   1%|          | 62/11059 [01:12<3:32:16,  1.16s/it]
Generating Summaries:   1%|          | 63/11059 [01:13<3:30:13,  1.15s/it]
Generating Summaries:   1%|          | 64/11059 [01:14<3:33:07,  1.16s/it]
Generating Summaries:   1%|          | 65/11059 [01:16<3:34:42,  1.17s/it]
Generating Summaries:   1%|          | 66/11059 [01:17<3:18:17,  1.08s/it]
Generating Summaries:   1%|          | 67/11059 [01:18<3:17:57,  1.08s/it]
Generating Summaries:   1%|          | 68/11059 [01:19<3:23:11,  1.11s/it]
Generating Summaries:   1%|          | 69/11059 [01:20<3:18:53,  1.09s/it]
Generating Summaries:   1%|          | 70/11059 [01:21<3:39:49,  1.20s/it]
Generating Summaries:   1%|          | 71/11059 [01:22<3:36:02,  1.18s/it]
Generating Summaries:   1%|          | 72/11059 [01:24<3:41:40,  1.21s/it]
Generating Summaries:   1%|          | 73/11059 [01:25<3:21:08,  1.10s/it]
Generating Summaries:   1%|          | 74/11059 [01:26<3:15:16,  1.07s/it]
Generating Summaries:   1%|          | 75/11059 [01:27<3:22:04,  1.10s/it]
Generating Summaries:   1%|          | 76/11059 [01:28<3:18:43,  1.09s/it]
Generating Summaries:   1%|          | 77/11059 [01:29<3:03:25,  1.00s/it]
Generating Summaries:   1%|          | 78/11059 [01:30<3:03:00,  1.00it/s]
Generating Summaries:   1%|          | 79/11059 [01:31<3:24:50,  1.12s/it]
Generating Summaries:   1%|          | 80/11059 [01:32<3:30:26,  1.15s/it]
Generating Summaries:   1%|          | 81/11059 [01:34<3:39:04,  1.20s/it]
Generating Summaries:   1%|          | 82/11059 [01:35<3:40:37,  1.21s/it]
Generating Summaries:   1%|          | 83/11059 [01:36<3:41:58,  1.21s/it]
Generating Summaries:   1%|          | 84/11059 [01:37<3:22:24,  1.11s/it]
Generating Summaries:   1%|          | 85/11059 [01:38<3:13:47,  1.06s/it]
Generating Summaries:   1%|          | 86/11059 [01:39<3:41:49,  1.21s/it]
Generating Summaries:   1%|          | 87/11059 [01:41<3:50:26,  1.26s/it]
Generating Summaries:   1%|          | 88/11059 [01:42<3:45:45,  1.23s/it]
Generating Summaries:   1%|          | 89/11059 [01:43<3:34:44,  1.17s/it]
Generating Summaries:   1%|          | 90/11059 [01:44<3:32:05,  1.16s/it]
Generating Summaries:   1%|          | 91/11059 [01:45<3:38:36,  1.20s/it]
Generating Summaries:   1%|          | 92/11059 [01:46<3:19:10,  1.09s/it]
Generating Summaries:   1%|          | 93/11059 [01:47<3:17:08,  1.08s/it]
Generating Summaries:   1%|          | 94/11059 [01:48<3:17:32,  1.08s/it]
Generating Summaries:   1%|          | 95/11059 [01:50<3:25:38,  1.13s/it]
Generating Summaries:   1%|          | 96/11059 [01:51<3:31:23,  1.16s/it]
Generating Summaries:   1%|          | 97/11059 [01:52<3:29:33,  1.15s/it]
Generating Summaries:   1%|          | 98/11059 [01:53<3:42:25,  1.22s/it]
Generating Summaries:   1%|          | 99/11059 [01:54<3:17:48,  1.08s/it]
Generating Summaries:   1%|          | 100/11059 [01:55<3:09:01,  1.03s/it]
Generating Summaries:   1%|          | 101/11059 [01:56<3:17:49,  1.08s/it]
Generating Summaries:   1%|          | 102/11059 [01:58<3:33:45,  1.17s/it]
Generating Summaries:   1%|          | 103/11059 [01:59<3:28:26,  1.14s/it]
Generating Summaries:   1%|          | 104/11059 [02:00<3:17:52,  1.08s/it]
Generating Summaries:   1%|          | 105/11059 [02:01<3:37:05,  1.19s/it]
Generating Summaries:   1%|          | 106/11059 [02:03<3:55:03,  1.29s/it]
Generating Summaries:   1%|          | 107/11059 [02:03<3:35:12,  1.18s/it]
Generating Summaries:   1%|          | 108/11059 [02:04<3:12:45,  1.06s/it]
Generating Summaries:   1%|          | 109/11059 [02:05<3:14:05,  1.06s/it]
Generating Summaries:   1%|          | 110/11059 [02:06<3:03:58,  1.01s/it]
Generating Summaries:   1%|          | 111/11059 [02:08<3:27:47,  1.14s/it]
Generating Summaries:   1%|          | 112/11059 [02:09<3:46:36,  1.24s/it]
Generating Summaries:   1%|          | 113/11059 [02:10<3:30:11,  1.15s/it]
Generating Summaries:   1%|          | 114/11059 [02:12<3:49:58,  1.26s/it]
Generating Summaries:   1%|          | 115/11059 [02:13<4:07:21,  1.36s/it]
Generating Summaries:   1%|          | 116/11059 [02:14<3:36:05,  1.18s/it]
Generating Summaries:   1%|          | 117/11059 [02:15<3:46:16,  1.24s/it]
Generating Summaries:   1%|          | 118/11059 [02:16<3:31:25,  1.16s/it]
Generating Summaries:   1%|          | 119/11059 [02:17<3:18:30,  1.09s/it]
Generating Summaries:   1%|          | 120/11059 [02:18<3:26:54,  1.13s/it]
Generating Summaries:   1%|          | 121/11059 [02:19<3:14:08,  1.06s/it]
Generating Summaries:   1%|          | 122/11059 [02:21<3:35:27,  1.18s/it]
Generating Summaries:   1%|          | 123/11059 [02:22<3:22:45,  1.11s/it]
Generating Summaries:   1%|          | 124/11059 [02:23<3:20:45,  1.10s/it]
Generating Summaries:   1%|          | 125/11059 [02:24<3:06:30,  1.02s/it]
Generating Summaries:   1%|          | 126/11059 [02:25<3:29:11,  1.15s/it]
Generating Summaries:   1%|          | 127/11059 [02:26<3:15:52,  1.08s/it]
Generating Summaries:   1%|          | 128/11059 [02:27<3:13:26,  1.06s/it]
Generating Summaries:   1%|          | 129/11059 [02:28<3:28:17,  1.14s/it]
Generating Summaries:   1%|          | 130/11059 [02:30<3:41:28,  1.22s/it]
Generating Summaries:   1%|          | 131/11059 [02:31<4:00:50,  1.32s/it]
Generating Summaries:   1%|          | 132/11059 [02:33<4:00:40,  1.32s/it]
Generating Summaries:   1%|          | 133/11059 [02:34<4:05:14,  1.35s/it]
Generating Summaries:   1%|          | 134/11059 [02:36<4:16:41,  1.41s/it]
Generating Summaries:   1%|          | 135/11059 [02:37<4:15:30,  1.40s/it]
Generating Summaries:   1%|          | 136/11059 [02:38<4:07:43,  1.36s/it]
Generating Summaries:   1%|          | 137/11059 [02:39<3:46:37,  1.24s/it]
Generating Summaries:   1%|          | 138/11059 [02:40<3:43:47,  1.23s/it]
Generating Summaries:   1%|▏         | 139/11059 [02:42<3:54:49,  1.29s/it]
Generating Summaries:   1%|▏         | 140/11059 [02:43<4:10:12,  1.37s/it]
Generating Summaries:   1%|▏         | 141/11059 [02:45<4:06:52,  1.36s/it]
Generating Summaries:   1%|▏         | 142/11059 [02:46<3:59:09,  1.31s/it]
Generating Summaries:   1%|▏         | 143/11059 [02:47<3:43:47,  1.23s/it]
Generating Summaries:   1%|▏         | 144/11059 [02:48<3:39:50,  1.21s/it]
Generating Summaries:   1%|▏         | 145/11059 [02:49<3:33:14,  1.17s/it]
Generating Summaries:   1%|▏         | 146/11059 [02:50<3:28:26,  1.15s/it]
Generating Summaries:   1%|▏         | 147/11059 [02:51<3:22:30,  1.11s/it]
Generating Summaries:   1%|▏         | 148/11059 [02:52<3:15:48,  1.08s/it]
Generating Summaries:   1%|▏         | 149/11059 [02:53<3:15:11,  1.07s/it]
Generating Summaries:   1%|▏         | 150/11059 [02:54<2:59:58,  1.01it/s]
Generating Summaries:   1%|▏         | 151/11059 [02:56<3:26:18,  1.13s/it]
Generating Summaries:   1%|▏         | 152/11059 [02:57<3:34:09,  1.18s/it]
Generating Summaries:   1%|▏         | 153/11059 [02:58<3:31:32,  1.16s/it]
Generating Summaries:   1%|▏         | 154/11059 [02:59<3:33:13,  1.17s/it]
Generating Summaries:   1%|▏         | 155/11059 [03:00<3:10:24,  1.05s/it]
Generating Summaries:   1%|▏         | 156/11059 [03:01<3:06:48,  1.03s/it]
Generating Summaries:   1%|▏         | 157/11059 [03:02<3:06:40,  1.03s/it]
Generating Summaries:   1%|▏         | 158/11059 [03:03<2:52:35,  1.05it/s]
Generating Summaries:   1%|▏         | 159/11059 [03:04<3:20:48,  1.11s/it]
Generating Summaries:   1%|▏         | 160/11059 [03:05<3:19:27,  1.10s/it]
Generating Summaries:   1%|▏         | 161/11059 [03:06<3:19:44,  1.10s/it]
Generating Summaries:   1%|▏         | 162/11059 [03:08<3:47:27,  1.25s/it]
Generating Summaries:   1%|▏         | 163/11059 [03:10<4:01:43,  1.33s/it]
Generating Summaries:   1%|▏         | 164/11059 [03:10<3:38:39,  1.20s/it]
Generating Summaries:   1%|▏         | 165/11059 [03:11<3:26:33,  1.14s/it]
Generating Summaries:   2%|▏         | 166/11059 [03:12<3:17:36,  1.09s/it]
Generating Summaries:   2%|▏         | 167/11059 [03:13<3:11:58,  1.06s/it]
Generating Summaries:   2%|▏         | 168/11059 [03:15<3:13:58,  1.07s/it]
Generating Summaries:   2%|▏         | 169/11059 [03:16<3:16:38,  1.08s/it]
Generating Summaries:   2%|▏         | 170/11059 [03:17<3:43:14,  1.23s/it]
Generating Summaries:   2%|▏         | 171/11059 [03:18<3:44:39,  1.24s/it]
Generating Summaries:   2%|▏         | 172/11059 [03:20<4:02:27,  1.34s/it]
Generating Summaries:   2%|▏         | 173/11059 [03:21<3:34:04,  1.18s/it]
Generating Summaries:   2%|▏         | 174/11059 [03:22<3:27:15,  1.14s/it]
Generating Summaries:   2%|▏         | 175/11059 [03:23<3:20:43,  1.11s/it]
Generating Summaries:   2%|▏         | 176/11059 [03:24<3:22:48,  1.12s/it]
Generating Summaries:   2%|▏         | 177/11059 [03:25<3:25:56,  1.14s/it]
Generating Summaries:   2%|▏         | 178/11059 [03:26<3:29:21,  1.15s/it]
Generating Summaries:   2%|▏         | 179/11059 [03:28<3:53:20,  1.29s/it]
Generating Summaries:   2%|▏         | 180/11059 [03:29<3:48:56,  1.26s/it]
Generating Summaries:   2%|▏         | 181/11059 [03:30<3:45:18,  1.24s/it]
Generating Summaries:   2%|▏         | 182/11059 [03:32<3:37:02,  1.20s/it]
Generating Summaries:   2%|▏         | 183/11059 [03:33<3:38:45,  1.21s/it]
Generating Summaries:   2%|▏         | 184/11059 [03:34<3:37:17,  1.20s/it]
Generating Summaries:   2%|▏         | 185/11059 [03:35<3:21:24,  1.11s/it]
Generating Summaries:   2%|▏         | 186/11059 [03:36<3:39:53,  1.21s/it]
Generating Summaries:   2%|▏         | 187/11059 [03:37<3:27:52,  1.15s/it]
Generating Summaries:   2%|▏         | 188/11059 [03:38<3:26:11,  1.14s/it]
Generating Summaries:   2%|▏         | 189/11059 [03:40<3:24:14,  1.13s/it]
Generating Summaries:   2%|▏         | 190/11059 [03:41<3:28:06,  1.15s/it]
Generating Summaries:   2%|▏         | 191/11059 [03:42<3:15:21,  1.08s/it]
Generating Summaries:   2%|▏         | 192/11059 [03:43<3:29:51,  1.16s/it]
Generating Summaries:   2%|▏         | 193/11059 [03:44<3:27:33,  1.15s/it]
Generating Summaries:   2%|▏         | 194/11059 [03:45<3:19:12,  1.10s/it]
Generating Summaries:   2%|▏         | 195/11059 [03:46<3:04:06,  1.02s/it]
Generating Summaries:   2%|▏         | 196/11059 [03:47<3:15:00,  1.08s/it]
Generating Summaries:   2%|▏         | 197/11059 [03:48<3:18:27,  1.10s/it]
Generating Summaries:   2%|▏         | 198/11059 [03:49<3:18:44,  1.10s/it]
Generating Summaries:   2%|▏         | 199/11059 [03:51<3:22:47,  1.12s/it]
Generating Summaries:   2%|▏         | 200/11059 [03:52<3:44:09,  1.24s/it]
Generating Summaries:   2%|▏         | 201/11059 [03:53<3:39:06,  1.21s/it]
Generating Summaries:   2%|▏         | 202/11059 [03:55<3:49:18,  1.27s/it]
Generating Summaries:   2%|▏         | 203/11059 [03:56<3:51:10,  1.28s/it]
Generating Summaries:   2%|▏         | 204/11059 [03:57<4:02:34,  1.34s/it]
Generating Summaries:   2%|▏         | 205/11059 [03:59<3:53:20,  1.29s/it]
Generating Summaries:   2%|▏         | 206/11059 [04:00<3:52:05,  1.28s/it]
Generating Summaries:   2%|▏         | 207/11059 [04:01<3:39:45,  1.22s/it]
Generating Summaries:   2%|▏         | 208/11059 [04:02<3:22:54,  1.12s/it]
Generating Summaries:   2%|▏         | 209/11059 [04:03<3:24:43,  1.13s/it]
Generating Summaries:   2%|▏         | 210/11059 [04:04<3:24:53,  1.13s/it]
Generating Summaries:   2%|▏         | 211/11059 [04:05<3:23:22,  1.12s/it]
Generating Summaries:   2%|▏         | 212/11059 [04:07<3:36:30,  1.20s/it]
Generating Summaries:   2%|▏         | 213/11059 [04:08<3:31:36,  1.17s/it]
Generating Summaries:   2%|▏         | 214/11059 [04:09<3:47:32,  1.26s/it]
Generating Summaries:   2%|▏         | 215/11059 [04:10<3:38:09,  1.21s/it]
Generating Summaries:   2%|▏         | 216/11059 [04:12<3:54:32,  1.30s/it]
Generating Summaries:   2%|▏         | 217/11059 [04:13<3:30:50,  1.17s/it]
Generating Summaries:   2%|▏         | 218/11059 [04:14<3:45:12,  1.25s/it]
Generating Summaries:   2%|▏         | 219/11059 [04:15<3:20:16,  1.11s/it]
Generating Summaries:   2%|▏         | 220/11059 [04:16<3:09:07,  1.05s/it]
Generating Summaries:   2%|▏         | 221/11059 [04:17<2:58:00,  1.01it/s]
Generating Summaries:   2%|▏         | 222/11059 [04:18<3:01:09,  1.00s/it]
Generating Summaries:   2%|▏         | 223/11059 [04:18<2:52:10,  1.05it/s]
Generating Summaries:   2%|▏         | 224/11059 [04:19<2:48:27,  1.07it/s]
Generating Summaries:   2%|▏         | 225/11059 [04:20<3:00:37,  1.00s/it]
Generating Summaries:   2%|▏         | 226/11059 [04:22<3:02:36,  1.01s/it]
Generating Summaries:   2%|▏         | 227/11059 [04:23<3:32:22,  1.18s/it]
Generating Summaries:   2%|▏         | 228/11059 [04:24<3:24:55,  1.14s/it]
Generating Summaries:   2%|▏         | 229/11059 [04:25<3:17:19,  1.09s/it]
Generating Summaries:   2%|▏         | 230/11059 [04:27<3:42:29,  1.23s/it]
Generating Summaries:   2%|▏         | 231/11059 [04:28<3:43:02,  1.24s/it]
Generating Summaries:   2%|▏         | 232/11059 [04:29<3:30:49,  1.17s/it]
Generating Summaries:   2%|▏         | 233/11059 [04:30<3:34:25,  1.19s/it]
Generating Summaries:   2%|▏         | 234/11059 [04:32<3:54:44,  1.30s/it]
Generating Summaries:   2%|▏         | 235/11059 [04:33<3:58:28,  1.32s/it]
Generating Summaries:   2%|▏         | 236/11059 [04:35<4:11:54,  1.40s/it]
Generating Summaries:   2%|▏         | 237/11059 [04:35<3:40:43,  1.22s/it]
Generating Summaries:   2%|▏         | 238/11059 [04:37<3:50:05,  1.28s/it]
Generating Summaries:   2%|▏         | 239/11059 [04:38<4:07:35,  1.37s/it]
Generating Summaries:   2%|▏         | 240/11059 [04:40<3:48:36,  1.27s/it]
Generating Summaries:   2%|▏         | 241/11059 [04:41<3:42:23,  1.23s/it]
Generating Summaries:   2%|▏         | 242/11059 [04:42<4:00:23,  1.33s/it]
Generating Summaries:   2%|▏         | 243/11059 [04:43<3:28:21,  1.16s/it]
Generating Summaries:   2%|▏         | 244/11059 [04:44<3:18:55,  1.10s/it]
Generating Summaries:   2%|▏         | 245/11059 [04:45<3:25:56,  1.14s/it]
Generating Summaries:   2%|▏         | 246/11059 [04:46<3:23:09,  1.13s/it]
Generating Summaries:   2%|▏         | 247/11059 [04:47<3:28:32,  1.16s/it]
Generating Summaries:   2%|▏         | 248/11059 [04:49<3:40:03,  1.22s/it]
Generating Summaries:   2%|▏         | 249/11059 [04:50<3:41:25,  1.23s/it]
Generating Summaries:   2%|▏         | 250/11059 [04:52<4:01:02,  1.34s/it]
Generating Summaries:   2%|▏         | 251/11059 [04:53<3:51:39,  1.29s/it]
Generating Summaries:   2%|▏         | 252/11059 [04:54<3:37:04,  1.21s/it]
Generating Summaries:   2%|▏         | 253/11059 [04:55<3:44:48,  1.25s/it]
Generating Summaries:   2%|▏         | 254/11059 [04:57<3:45:34,  1.25s/it]
Generating Summaries:   2%|▏         | 255/11059 [04:57<3:25:43,  1.14s/it]
Generating Summaries:   2%|▏         | 256/11059 [04:58<3:17:58,  1.10s/it]
Generating Summaries:   2%|▏         | 257/11059 [05:00<3:20:10,  1.11s/it]
Generating Summaries:   2%|▏         | 258/11059 [05:01<3:19:46,  1.11s/it]
Generating Summaries:   2%|▏         | 259/11059 [05:02<3:09:38,  1.05s/it]
Generating Summaries:   2%|▏         | 260/11059 [05:03<3:18:24,  1.10s/it]
Generating Summaries:   2%|▏         | 261/11059 [05:04<3:42:55,  1.24s/it]
Generating Summaries:   2%|▏         | 262/11059 [05:05<3:37:57,  1.21s/it]
Generating Summaries:   2%|▏         | 263/11059 [05:07<3:44:12,  1.25s/it]

CPU times: user 3h 33min 58s, sys: 13.2 s, total: 3h 34min 11s
Wall time: 3h 33min 52s

In [15]:
Summaries['T5Summary'] = SystemSummary1

In [16]:
Summaries.head()

,GoldSummary,BartSummary,T5Summary
0,गुजरात के मुख्यमंत्री नरेंद्र मोदी ने अमरीकी न...,ग़ौरतलब है कि अमरीका ने पिछले सप्ताह नरेंद्र म...,भारत के प्रधानमंत्री नरेंद्र मोदी ने अमरीका मे...
1,जनता कर्फ़्यू को गंभीरता से लेने पर प्रधानमंत्...,उन्होंने ट्वीट किया है कि 'देशवासियों ने बता द...,भारत के प्रधानमंत्री नरेंद्र मोदी ने कहा है कि...
2,भारत के राष्ट्रपति डॉ. एपीजे अब्दुल कलाम ने मध...,"उन्होंने कहा कि सड़क, बिजली और कंप्यूटर जैसी स...",भारत के राष्ट्रपति एपीजे अब्दुल कलाम ने कहा है...
3,मोहाली टेस्ट के चौथे दिन ऑस्ट्रेलिया ने 516 रन...,सोमवार को भारत ने अपनी दूसरी पारी कुल 314 रन ब...,भारत और ऑस्ट्रेलिया के बीच सिडनी में खेले जा र...
4,टेस्ट मैच शृंखला के लिए भारत पहुंची ऑस्ट्रेलिय...,भारत के दौरे में रिकी पोंटिंग अक्सर स्पिन गेंद...,ऑस्ट्रेलियाई क्रिकेट टीम के कप्तान रिकी पोंटिं...

In [17]:
rouge = Rouge()
score = rouge.get_scores(Summaries['T5Summary'], Summaries['GoldSummary'], avg=True)
T5Rouge = pd.DataFrame(score).set_index([['recall','precision','f-measure']])
T5Rouge

            rouge-1   rouge-2   rouge-l
recall     0.347126  0.146683  0.300180
precision  0.437316  0.191032  0.377572
f-measure  0.376852  0.160993  0.325595

### **Plotting Rouge Score**

In [18]:
T5Rouge = T5Rouge[['rouge-1','rouge-l', 'rouge-2']]
BartRouge = BartRouge[['rouge-1','rouge-l', 'rouge-2']]

In [19]:
fig = px.bar(T5Rouge*100, x=T5Rouge.index, y=T5Rouge.columns, 
             barmode='group', 
             text_auto='.2s',
             labels={
                     "Algo": "Algorithms",
                     "value": "Rouge Score",
                     "variable": "legend",
                     'index': "Metrics"
                 })

fig.update_layout(width=650,
                  height=400,
                  title={
                  'text': "Score",
                  'y':.96,
                  'x':0.49,
                  'xanchor': 'center',
                  'yanchor': 'top'})

fig.show()

In [20]:
fig = px.bar(BartRouge*100, x=BartRouge.index, y=BartRouge.columns, 
             barmode='group', 
             text_auto='.2s',
             labels={
                     "Algo": "Algorithms",
                     "value": "Rouge Score",
                     "variable": "legend",
                     'index': "Metrics"
                 })
fig.update_layout( width=650,
                  height=400,
                title={
                  'text': "Score",
                  'y':.96,
                  'x':0.49,
                  'xanchor': 'center',
                  'yanchor': 'top'})

fig.show()

### **Sample Summaries**

In [21]:
[i for i in Summaries['GoldSummary'][:5]]

['गुजरात के मुख्यमंत्री नरेंद्र मोदी ने अमरीकी न्यूयॉर्क में एक जनसभा को उपग्रह के ज़रिए संबोधित किया है.',
 'जनता कर्फ़्यू को गंभीरता से लेने पर प्रधानमंत्री नरेंद्र मोदी ने भारत के लोगों की तारीफ़ की है.',
 'भारत के राष्ट्रपति डॉ. एपीजे अब्दुल कलाम ने मध्यप्रदेश के ईटखेड़ी गाँव के बच्चों से कहा कि वो शहरी और ग्रामीण जीवन के अंतर को दूर करने का सपना देखें.',
 'मोहाली टेस्ट के चौथे दिन ऑस्ट्रेलिया ने 516 रनों के लक्ष्य का पीछा करते हुए पाँच विकेट पर 141 रन बनाए लिए हैं.',
 'टेस्ट मैच शृंखला के लिए भारत पहुंची ऑस्ट्रेलियाई टीम के कप्तान रिकी पोंटिंग का कहना है कि वो भारत के स्पिन आक्रमण के लिए पूरी तरह तैयार हैं.']

In [22]:
[i for i in Summaries['T5Summary'][:5]]

['भारत के प्रधानमंत्री नरेंद्र मोदी ने अमरीका में एक जनसभा को संबोधित करते हुए कहा है कि माँ भारती के माथे पर काला टीका लगाया गया है.',
 'भारत के प्रधानमंत्री नरेंद्र मोदी ने कहा है कि देश में कोरोना वायरस संक्रमण के मामले बढ़ रहे हैं.',
 'भारत के राष्ट्रपति एपीजे अब्दुल कलाम ने कहा है कि अंतरिक्ष विज्ञान के क्षेत्र में बच्चों को सुविधाएँ मिलनी चाहिए.',
 'भारत और ऑस्ट्रेलिया के बीच सिडनी में खेले जा रहे दूसरे टेस्ट मैच में भारत ने पहली पारी में 131 रन बना लिए हैं.',
 'ऑस्ट्रेलियाई क्रिकेट टीम के कप्तान रिकी पोंटिंग का कहना है कि वो भारत के दौरे के लिए स्पिन गेंदबाज़ी करेंगे.']

In [23]:
[i for i in Summaries['BartSummary'][:5]]

['ग़ौरतलब है कि अमरीका ने पिछले सप्ताह नरेंद्र मोदी को यह कहते हुए वीज़ा देने से इनकार कर दिया था कि मोदी ने धार्मिक स्वतंत्रता का उल्लंघन किया है. मोदी को वीज़ा नहीं दिए जाने के मुद्दे ने काफ़ी तूल पकड़ा था और भारत सरकार ने इस मुद्दे पर अमरीका सरकार से नाराज़गी जताई थी. नरेंद्र मोदी अमरीका तो नहीं जा',
 "उन्होंने ट्वीट किया है कि 'देशवासियों ने बता दिया कि हम सक्षम हैं. लेकिन यह एक लंबी लड़ाई की शुरुआत है.' पीएम मोदी ने दो दिन पहले, 22 मार्च को एक दिवसीय कर्फ़्यू लगाने की घोषणा की थी. लेकिन इस 'लड़ाई' की गंभीरता को देखते हुए भारत सरकार ने रविवार शाम देश के 22 राज्यों",
 'उन्होंने कहा कि सड़क, बिजली और कंप्यूटर जैसी सुविधाएँ गाँवों को भी मिलनी चाहिए. वह मंगलवार को भोपाल से नौ किलोमीटर दूर ईटखेड़ी के एक स्कूल के दौरे पर थे. राष्ट्रपति कलाम ने बच्चों से दोहराने को कहा, "सपने, सपने, सपने...सपनों को विचारों में बदलिए...और',
 'सोमवार को भारत ने अपनी दूसरी पारी कुल 314 रन बनाकर पारी घोषित कर दी थी. इस तरह अब ऑस्ट्रेलिया को जीत के लिए कुल 516 बनाने होंगे. ज़ाहिर है अब दबाव ऑस्ट्रेलिया की टीम पर है या तो 516 का विशाल स्कोर बनाए या फिर मैच को ड्रॉ करवाए. चौथे दिन ऑस्ट्रेलिया की शुरुआत ख़राब रही. हेडन (29',
 "भारत के दौरे में रिकी पोंटिंग अक्सर स्पिन गेंदबाज़ी के ख़िलाफ़ बहुत अच्छा प्रदर्शन नहीं कर पाए हैं लेकिन उनका कहना है कि वो इस बार अलग रवैए के साथ आए हैं. रेडियो ऑस्ट्रेलिया के साथ एक बातचीत में पोंटिंग का कहना था, ' हमने इस शृंखला से पहले ही तय कर लिया था कि भारत की परिस्थितियों"]